# Generated by Django 4.1.5 on 2023-05-16 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0003_review_ebook_review_reviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='cover_image',
            field=models.ImageField(upload_to='covers/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='pdf',
            field=models.FileField(upload_to='pdfs/%Y/%m/%d/'),
        ),
    ]
